# Generated by Django 5.2.6 on 2025-10-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
