# Generated by Django 5.2.6 on 2025-10-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='current_status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered')], db_index=True, default='NEW', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='statusupdate',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered')], db_index=True, max_length=20),
        ),
    ]
