# Generated by Django 5.2.6 on 2025-11-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_alter_shipment_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='KG', max_length=50),
        ),
    ]
