# Generated by Django 5.2.6 on 2025-11-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of product units in this shipment'),
        ),
    ]
