# Generated by Django 5.2.6 on 2025-11-12 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_shipment_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Saudi phone number (e.g., +966512345678 or 966512345678)', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Saudi number starting with +966 or 966 followed by 9 digits.', regex='^\\+?966\\d{9}$')]),
        ),
    ]
