"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import sys
import environ
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

env = environ.Env()

env_file = BASE_DIR / ".env"
if env_file.exists():
    environ.Env.read_env(env_file)

SECRET_KEY = env("DJANGO_SECRET_KEY")             
DEBUG = env.bool("DEBUG", default=False)

if not DEBUG and not SECRET_KEY:
    raise RuntimeError("DJANGO_SECRET_KEY must be set in production.")



# Application definition
INSTALLED_APPS = [
    # Admin theme
    'jazzmin',

    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    "corsheaders",
    "rest_framework",                
    "rest_framework_simplejwt",        
    "drf_spectacular",
    
    # Project apps
    "shipments",
    "users",
]

JAZZMIN_SETTINGS = {
    # Site branding
    "site_title": "RouteX Control Panel",
    "site_header": "🚚 RouteX - Logistics Management System",
    "site_brand": "RouteX",
    "welcome_sign": "Welcome to RouteX Control Center",
    "copyright": "RouteX © 2025",
    
    # Custom CSS
    "custom_css": "users/css/admin.css",
    "custom_js": None,
    
    # Logo
    "site_logo": None,
    "site_logo_classes": "img-circle elevation-3",
    "site_icon": None,
    
    # Top menu links
    "topmenu_links": [
        {"name": "🏠 Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "📊 Reports", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "📖 API Docs", "url": "/api/docs/", "new_window": True},
        {"name": "💻 Swagger UI", "url": "/api/docs/swagger-ui/", "new_window": True},
    ],
    
    # User menu links
    "usermenu_links": [
        {"name": "🌐 Visit Site", "url": "/", "new_window": True},
        {"name": "📚 API Documentation", "url": "/api/docs/", "new_window": True},
        {"model": "users.CustomUser"},
    ],
    
    # Side menu customization
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    
    # Order of apps and models
    "order_with_respect_to": [
        "users",
        "users.CustomUser",
        "shipments",
        "shipments.Driver",
        "shipments.WarehouseManager",
        "shipments.Shipment",
        "shipments.Product",
        "shipments.Warehouse",
        "shipments.Customer",
        "shipments.StatusUpdate",
    ],
    
    # Custom app and model names
    "custom_links": {
        "users": [{
            "name": "Quick Add User",
            "url": "admin:users_customuser_add",
            "icon": "fas fa-user-plus",
            "permissions": ["users.add_customuser"]
        }],
        "shipments": [
            {
                "name": "Create Shipment",
                "url": "admin:shipments_shipment_add",
                "icon": "fas fa-shipping-fast",
                "permissions": ["shipments.add_shipment"]
            },
            {
                "name": "Add Product",
                "url": "admin:shipments_product_add",
                "icon": "fas fa-box-open",
                "permissions": ["shipments.add_product"]
            },
        ],
    },
    
    # Icons configuration
    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.Group": "fas fa-users",
        "users": "fas fa-user-circle",
        "users.CustomUser": "fas fa-user",
        "shipments": "fas fa-truck-loading",
        "shipments.Driver": "fas fa-truck",
        "shipments.WarehouseManager": "fas fa-user-tie",
        "shipments.Shipment": "fas fa-box",
        "shipments.Product": "fas fa-box-open",
        "shipments.Warehouse": "fas fa-warehouse",
        "shipments.Customer": "fas fa-users",
        "shipments.StatusUpdate": "fas fa-stream",
    },
    
    # Default icon for models
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    # Related modal
    "related_modal_active": False,
    
    # UI Tweaks
    "show_ui_builder": False,
    
    # Change view
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "users.CustomUser": "horizontal_tabs",
        "shipments.Shipment": "horizontal_tabs",
    },
    
    # Language chooser
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "cosmo",
    "navbar": "navbar-dark bg-primary",
    "sidebar": "sidebar-dark-primary",
    "actions_sticky_top": True,
    "body_small_text": False,
    "brand_logo": "",
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS must be before CommonMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware", 
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'RouteX.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'RouteX.wsgi.application'
AUTH_USER_MODEL = "users.CustomUser"   


LANGUAGE_CODE = 'en-us'
TIME_ZONE = "Asia/Riyadh"
USE_I18N = True
USE_TZ = True


SIMPLE_JWT = {
    # Reduced token lifetimes for better security
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),  # Reduced to 12h 
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),  # Reduced from 7d to 30d
    
    # Token rotation for enhanced security
    "ROTATE_REFRESH_TOKENS": True,  # Generate new refresh token on each use
    "BLACKLIST_AFTER_ROTATION": True,  # Blacklist old refresh tokens
    
    # Authentication header
    "AUTH_HEADER_TYPES": ("Bearer",),
    
    # Additional security settings
    "UPDATE_LAST_LOGIN": True,  # Update last_login on token refresh
    "ALGORITHM": "HS256",  # Use HS256 algorithm
}




# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use SQLite for development if PostgreSQL is not available
USE_SQLITE = env.bool("USE_SQLITE", default=False)

# ============================================================================
# CACHING CONFIGURATION - Redis for performance
# ============================================================================

# Redis cache configuration
# Falls back to local memory cache if Redis is not available
REDIS_URL = env.str("REDIS_URL", default="redis://127.0.0.1:6379/1")
USE_REDIS = env.bool("USE_REDIS", default=False)

if USE_REDIS:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "SOCKET_CONNECT_TIMEOUT": 5,  # 5 seconds
                "SOCKET_TIMEOUT": 5,
                "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
                "IGNORE_EXCEPTIONS": True,  # Don't crash if Redis is down
            },
            "KEY_PREFIX": "routex",
            "TIMEOUT": 300,  # 5 minutes default timeout
        }
    }
else:
    # Fallback to local memory cache for development
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
            "TIMEOUT": 300,  # 5 minutes
        }
    }

if USE_SQLITE or not os.getenv("DB_NAME"):
    # SQLite configuration (easier for local development)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    # PostgreSQL configuration (production)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "routex"),
            "USER": os.getenv("DB_USER", "routex_user"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "127.0.0.1"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }


# Date and time format with 12-hour clock 
# Adjust TIME_12 based on your operating system for compatibility

TIME_12 = "%-I:%M%p" if sys.platform != "win32" else "%#I:%M%p"

REST_FRAMEWORK = {
    # Authentication
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    
    # Permissions
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),

    # Pagination - professional settings for large datasets
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 10,
    
    # Throttling - protect API from abuse
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",      # Anonymous users
        "user": "2000/hour",     # Authenticated users
        "driver": "5000/hour",   # Drivers need more for status updates
        "manager": "10000/hour", # Managers need high limits
    },
    
    # Schema generation for API documentation
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    
    # Date/time formatting
    "DATETIME_FORMAT": f"%Y-%m-%d {TIME_12}",
    
    # Exception handling - consistent error responses
    "EXCEPTION_HANDLER": "rest_framework.views.exception_handler",
    
    # Filtering, searching, ordering
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],

    # Tests: force JSON format for test client to avoid multipart None encoding issues
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
}

# API Documentation settings (drf-spectacular)
SPECTACULAR_SETTINGS = {
    "TITLE": "RouteX Logistics API",
    "DESCRIPTION": "Professional REST API for logistics and shipment management system. "
                   "Supports role-based access control for Warehouse Managers and Drivers.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },
    "AUTHENTICATION_WHITELIST": [],
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"



# ============================================================================
# HOSTS & DOMAIN CONFIGURATION
# ============================================================================

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "zahraaayop.pythonanywhere.com",
    ".pythonanywhere.com",
    ".ngrok-free.app",          
]

CSRF_TRUSTED_ORIGINS = [
    "https://zahraaayop.pythonanywhere.com",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "https://*.ngrok-free.app",  
]


# ============================================================================
# CORS CONFIGURATION - Professional setup for external clients
# ============================================================================

# Read CORS origins from environment variable for flexibility
# Format in .env: CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
CORS_ALLOWED_ORIGINS_ENV = env.list("CORS_ALLOWED_ORIGINS", default=[])
ALLOW_LOCALHOST_CORS = env.bool("CORS_ALLOW_LOCALHOST", default=False)

if CORS_ALLOWED_ORIGINS_ENV:
    # Production: use explicit whitelist from .env
    CORS_ALLOWED_ORIGINS = CORS_ALLOWED_ORIGINS_ENV
    CORS_ALLOW_ALL_ORIGINS = False
elif DEBUG:
    # Development: allow any localhost origin (any port)
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = [
        "http://localhost",
        "http://127.0.0.1",
    ]
else:
    # Production fallback: no CORS unless explicitly configured
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = []

# Optionally allow any localhost (any port) in production via env flag
if ALLOW_LOCALHOST_CORS:
    # Regexes evaluated in addition to explicit origins
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://localhost:\d+$",
        r"^http://127\.0\.0\.1:\d+$",
    ]

# CORS security settings
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Allow typical HTTP verbs and preflight OPTIONS
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
    "HEAD",
]
CORS_PREFLIGHT_MAX_AGE = 86400  # cache preflight for one day


# ============================================================================
# SECURITY SETTINGS - Production hardening
# ============================================================================

if not DEBUG:
    # HTTPS/SSL settings for production
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=True)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=31536000)  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Cookie security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
    
    # Content Security Policy headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"
    
else:
    # Development: relaxed settings for easier testing
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False


# ============================================================================
# FILE UPLOAD SETTINGS - Security and size limits
# ============================================================================

# Maximum upload size: 10MB for images
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Allowed image formats for products and status updates
ALLOWED_IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.webp']
MAX_IMAGE_SIZE = 5 * 1024 * 1024  # 5MB per image